### PR TITLE
enhance and prettify

### PR DESCRIPTION
**Pull request by electriquo**

### CODE REVIEW

**Comment by electriquo** [comment]
@gdi3d anything before a review is requested?

**Comment by electriquo** [comment]
@gdi3d friendly ping

**Comment by gdi3d** [comment]
Hey, I'm quite busy these days. I reviewed the code and there are some good changes proposed, but is not solving any really issues. I like to keep the script as simple possible for all audiences so I'm not going to accept the PR, sorry.

**Comment by electriquo** [comment]
@gdi3d it does improve many things, such as error catching and handling, it is more posix compatible, etc. i am going to keep the fork and i hope it won't draw any focus from yours.

thanks.

**Pull request closed without merging**
